export const NATS_SERVICE = 'NATS_SERVICE';
export const PRISMA_CLIENT = 'PRISMA_CLIENT';
export const SNOWFLAKE_ID_GENERATOR = 'SNOWFLAKE_ID_GENERATOR';
export const DOMAIN_EVENT_CONSUMER = 'DOMAIN_EVENT_CONSUMER';
